language: ruby
rvm:
  - 1.9.3
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head

cache: bundler

script: bundle exec rake

notifications:
  email: false

sudo: false

git:
  depth: 10

matrix:
  allow_failures:
    - rvm: ruby-head
